apiVersion: v1
kind: Service
metadata:
  name: {{ include "trifle-io.fullname" . }}
  labels:
    {{- include "trifle-io.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "trifle-io.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
